# Generated by Django 4.1 on 2022-11-21 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam_finder', '0005_spam'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='spam_finder.contacts')),
                ('spam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='spam_finder.spam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
