# Generated by Django 4.1 on 2022-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_finder', '0008_remove_globaldata_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaldata',
            name='user',
        ),
        migrations.AddField(
            model_name='globaldata',
            name='name',
            field=models.CharField(default='mathew', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globaldata',
            name='phone_number',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globaldata',
            name='spam',
            field=models.CharField(default='Spam', max_length=255),
        ),
    ]
