# Generated by Django 4.1 on 2022-11-22 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam_finder', '0010_usercontacts_delete_globaldata_remove_spam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
