# Generated by Django 4.1 on 2022-11-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam_finder', '0011_usercontacts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='contact',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='usercontacts',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spam',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='spam',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spam_finder.contacts'),
        ),
    ]
